CREATE TABLE "User" (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName               VARCHAR(100) NOT NULL,
    lastName                VARCHAR(100) NOT NULL,
    email                   VARCHAR(255) NOT NULL UNIQUE,
    studentNumber           VARCHAR(32) NOT NULL UNIQUE,
    passwordHash            VARCHAR(255) NOT NULL,
    role                    VARCHAR(20) NOT NULL DEFAULT 'USER',
    programmeId             BIGINT,
    currentSemesterNumber   INTEGER,
    createdAt               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastLoginAt             TIMESTAMP WITH TIME ZONE,
    lastActiveAt            TIMESTAMP WITH TIME ZONE,
    CONSTRAINT chk_user_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE INDEX idx_user_email ON "User"(email);
CREATE INDEX idx_user_student_number ON "User"(studentNumber);

CREATE TABLE PasswordResetToken (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId              BIGINT NOT NULL REFERENCES "User"(id),
    tokenHash           VARCHAR(64) NOT NULL,
    expiresAt           TIMESTAMP WITH TIME ZONE NOT NULL,
    usedAt              TIMESTAMP WITH TIME ZONE,
    createdAt           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_passwordresettoken_user ON PasswordResetToken(userId);
CREATE INDEX idx_passwordresettoken_hash ON PasswordResetToken(tokenHash);
