CREATE TABLE Programme (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(32) NOT NULL UNIQUE,
    name                VARCHAR(255) NOT NULL,
    streamName          VARCHAR(255),
    description         CLOB,
    createdAt           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_programme_code ON Programme(code);

CREATE TABLE Course (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programmeId         BIGINT NOT NULL REFERENCES Programme(id),
    semesterNumber      INTEGER NOT NULL,
    name                VARCHAR(255) NOT NULL,
    code                VARCHAR(32),
    iconUrl             CLOB,
    description         CLOB,
    status              VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',
    createdByAdminId    BIGINT NOT NULL REFERENCES "User"(id),
    createdAt           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_course_status CHECK (status IN ('PUBLISHED', 'HIDDEN', 'ARCHIVED'))
);

CREATE INDEX idx_course_programme_semester ON Course(programmeId, semesterNumber, status);
CREATE INDEX idx_course_status ON Course(status);

ALTER TABLE "User"
    ADD CONSTRAINT fk_user_programme FOREIGN KEY (programmeId) REFERENCES Programme(id);
