CREATE TABLE UserCourse (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId              BIGINT NOT NULL REFERENCES "User"(id),
    courseId            BIGINT NOT NULL REFERENCES Course(id),
    sourceUserCourseId  BIGINT REFERENCES UserCourse(id),
    addedAt             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    isArchived          BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_usercourse_user_course ON UserCourse(userId, courseId);
CREATE INDEX idx_usercourse_archived ON UserCourse(isArchived);

CREATE TABLE StoredFile (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sha256Hash          VARCHAR(64) NOT NULL UNIQUE,
    storageUrl          CLOB NOT NULL,
    originalFilename    VARCHAR(512) NOT NULL,
    mimeType            VARCHAR(128) NOT NULL,
    fileSize            BIGINT NOT NULL,
    createdAt           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_storedfile_hash ON StoredFile(sha256Hash);

CREATE TABLE Material (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    courseId            BIGINT NOT NULL REFERENCES Course(id),
    userCourseId        BIGINT REFERENCES UserCourse(id),
    uploadedByUserId    BIGINT REFERENCES "User"(id),
    storedFileId        BIGINT REFERENCES StoredFile(id),
    title               VARCHAR(255) NOT NULL,
    description         CLOB,
    materialType        VARCHAR(30) NOT NULL,
    "year"              INTEGER,
    visibility          VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
    displayOrder        INTEGER,
    isOfficial          BOOLEAN NOT NULL DEFAULT FALSE,
    externalUrl         CLOB,
    videoId             VARCHAR(128),
    thumbnailUrl        CLOB,
    createdAt           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_material_visibility CHECK (visibility IN ('PUBLIC', 'SHARED', 'PRIVATE')),
    CONSTRAINT chk_material_type CHECK (materialType IN ('EXAM_PAPER', 'SOLUTION', 'LEARNING_MATERIAL', 'IMAGE', 'VIDEO', 'OTHER'))
);

CREATE INDEX idx_material_course_visibility ON Material(courseId, visibility, displayOrder);
CREATE INDEX idx_material_usercourse ON Material(userCourseId);
CREATE INDEX idx_material_type ON Material(materialType);

CREATE TABLE ShareInviteLink (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userCourseId        BIGINT NOT NULL REFERENCES UserCourse(id),
    token               VARCHAR(64) NOT NULL UNIQUE,
    label               VARCHAR(128),
    createdAt           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expiresAt           TIMESTAMP WITH TIME ZONE,
    revokedAt           TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_shareinvitelink_token ON ShareInviteLink(token);
CREATE INDEX idx_shareinvitelink_usercourse ON ShareInviteLink(userCourseId);

CREATE TABLE SharedCourseAccess (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userCourseId        BIGINT NOT NULL REFERENCES UserCourse(id),
    sharedWithUserId    BIGINT NOT NULL REFERENCES "User"(id),
    shareInviteLinkId   BIGINT REFERENCES ShareInviteLink(id),
    createdAt           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revokedAt           TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_sharedaccess_usercourse ON SharedCourseAccess(userCourseId);

CREATE TABLE WorkspaceState (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId              BIGINT NOT NULL REFERENCES "User"(id),
    courseId            BIGINT NOT NULL REFERENCES Course(id),
    userCourseId        BIGINT REFERENCES UserCourse(id),
    leftMaterialId      BIGINT REFERENCES Material(id),
    rightMaterialId     BIGINT REFERENCES Material(id),
    leftPage            INTEGER,
    rightPage           INTEGER,
    leftScrollPosition  DOUBLE,
    rightScrollPosition DOUBLE,
    leftZoom            DOUBLE,
    rightZoom           DOUBLE,
    dividerPosition     DOUBLE,
    activePanel         VARCHAR(10),
    viewMode            VARCHAR(10) NOT NULL DEFAULT 'DUAL',
    updatedAt           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_workspace_view_mode CHECK (viewMode IN ('SINGLE', 'DUAL')),
    CONSTRAINT chk_workspace_active_panel CHECK (activePanel IS NULL OR activePanel IN ('LEFT', 'RIGHT'))
);

CREATE UNIQUE INDEX idx_workspacestate_user_course ON WorkspaceState(userId, courseId, userCourseId);
